# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [7]:
import pandas as pd
import numpy as np

### Step 2. Create 3 differents Series, each of length 100, as follows: 
1. The first a random number from 1 to 4 
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [10]:
first = pd.Series(np.random.randint(1, 5, size = 100))
second = pd.Series(np.random.randint(1, 4, size = 100))
third = pd.Series(np.random.randint(10000, 30000, size = 100))

third

0     25536
1     16231
2     21714
3     27131
4     19252
      ...
95    12112
96    15021
97    19060
98    16257
99    26742
Length: 100, dtype: int64

### Step 3. Let's create a DataFrame by joinning the Series by column

In [ ]:
df = pd.DataFrame()

df["first"] = first
df["second"] = second
df["third"] = third

df

    first  second  third
0       1       2  25536
1       2       2  16231
2       2       2  21714
3       4       3  27131
4       3       1  19252
..    ...     ...    ...
95      1       3  12112
96      3       2  15021
97      2       3  19060
98      4       1  16257
99      1       1  26742

[100 rows x 3 columns]

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [19]:
df.rename(columns = {"first": "bedrs", "second": "bathrs", "third": "price_sqr_meter"})

    bedrs  bathrs  price_sqr_meter
0       1       2            25536
1       2       2            16231
2       2       2            21714
3       4       3            27131
4       3       1            19252
..    ...     ...              ...
95      1       3            12112
96      3       2            15021
97      2       3            19060
98      4       1            16257
99      1       1            26742

[100 rows x 3 columns]

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [23]:
# join concat the values
bigcolumn = pd.concat([first, second, third], axis=0)

# it is still a Series, so we need to transform it to a DataFrame
bigcolumn = bigcolumn.to_frame()
print(type(bigcolumn))

bigcolumn

<class 'pandas.DataFrame'>

        0
0       1
1       2
2       2
3       4
4       3
..    ...
95  12112
96  15021
97  19060
98  16257
99  26742

[300 rows x 1 columns]

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [24]:
len(bigcolumn)

300

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [28]:
bigcolumn.index = [i for i in range (300)]

bigcolumn

         0
0        1
1        2
2        2
3        4
4        3
..     ...
295  12112
296  15021
297  19060
298  16257
299  26742

[300 rows x 1 columns]